version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-name: "playwright"
    versioning-strategy: increase
    ignore:
      - dependency-name: "playwright"
        update-types: ["version-update:semver-patch"] # patches do not include browser version updates
