on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm ci

      - name: Install Chrome
        run: npx playwright install-deps chrome

      - name: Install Firefox
        run: npx playwright install-deps firefox

      - name: Run tests
        run: npm test